---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prometheus-cluster
  region: ap-southeast-1

vpc:
  cidr: 10.65.0.0/16
  autoAllocateIPv6: false
  nat:
    gateway: HighlyAvailable

nodeGroups:
  - name: PublicNodeGroup-1
    instanceType: t2.large
    minSize: 1
    maxSize: 9
    desiredCapacity: 3
    volumeSize: 100
    volumeType: gp2
    ssh:
      publicKeyName: ssh-key
      allow: true
    privateNetworking: true